"""Add privacy fields

Revision ID: 2962d68606a3
Revises: 
Create Date: 2026-08-07 15:44:48.067840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2962d68606a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Agent_Age', sa.Integer(), nullable=True),
    sa.Column('Agent_Rating', sa.Float(), nullable=True),
    sa.Column('Weather', sa.String(), nullable=True),
    sa.Column('Traffic', sa.String(), nullable=True),
    sa.Column('Vehicle', sa.String(), nullable=True),
    sa.Column('Area', sa.String(), nullable=True),
    sa.Column('Delivery_Time', sa.Integer(), nullable=True),
    sa.Column('customer_answered_call', sa.String(), nullable=True),
    sa.Column('customer_response_time', sa.Integer(), nullable=True),
    sa.Column('customer_availability', sa.String(), nullable=True),
    sa.Column('visitor_pass_status', sa.String(), nullable=True),
    sa.Column('society_security_level', sa.String(), nullable=True),
    sa.Column('gate_wait_time', sa.Integer(), nullable=True),
    sa.Column('driver_status', sa.String(), nullable=True),
    sa.Column('previous_failed_deliveries', sa.Integer(), nullable=True),
    sa.Column('address_confidence', sa.Float(), nullable=True),
    sa.Column('preferred_delivery_slot', sa.String(), nullable=True),
    sa.Column('estimated_arrival_delay', sa.Integer(), nullable=True),
    sa.Column('driver_experience', sa.Integer(), nullable=True),
    sa.Column('pickup_delay_minutes', sa.Float(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('is_weekend', sa.Integer(), nullable=True),
    sa.Column('arrival_within_preferred_slot', sa.Integer(), nullable=True),
    sa.Column('customer_reachability_score', sa.Float(), nullable=True),
    sa.Column('society_accessibility_score', sa.Float(), nullable=True),
    sa.Column('driver_reliability_score', sa.Float(), nullable=True),
    sa.Column('predictive_contact_consent', sa.Boolean(), nullable=True),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_cases_id'), 'delivery_cases', ['id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_case_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.Enum('system', 'ml_model', 'llm_agent', 'dispatcher', 'driver', 'customer', name='actorenum'), nullable=True),
    sa.Column('action_details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_case_id'], ['delivery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_id'), 'agent_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Agent_Age', sa.INTEGER(), nullable=True),
    sa.Column('Agent_Rating', sa.FLOAT(), nullable=True),
    sa.Column('Store_Latitude', sa.FLOAT(), nullable=True),
    sa.Column('Store_Longitude', sa.FLOAT(), nullable=True),
    sa.Column('Drop_Latitude', sa.FLOAT(), nullable=True),
    sa.Column('Drop_Longitude', sa.FLOAT(), nullable=True),
    sa.Column('Weather', sa.INTEGER(), nullable=True),
    sa.Column('Traffic', sa.INTEGER(), nullable=True),
    sa.Column('Vehicle', sa.INTEGER(), nullable=True),
    sa.Column('Area', sa.INTEGER(), nullable=True),
    sa.Column('Category', sa.INTEGER(), nullable=True),
    sa.Column('Delivery_Time', sa.INTEGER(), nullable=True),
    sa.Column('pin_code', sa.INTEGER(), nullable=True),
    sa.Column('driver_on_time_rate', sa.FLOAT(), nullable=True),
    sa.Column('customer_unavailability_history', sa.FLOAT(), nullable=True),
    sa.Column('address_failure_history_rate', sa.FLOAT(), nullable=True),
    sa.Column('order_value', sa.INTEGER(), nullable=True),
    sa.Column('slot_width_minutes', sa.INTEGER(), nullable=True),
    sa.Column('distance_km', sa.FLOAT(), nullable=True),
    sa.Column('risk_score', sa.FLOAT(), nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), nullable=True),
    sa.Column('month', sa.INTEGER(), nullable=True),
    sa.Column('is_weekend', sa.INTEGER(), nullable=True),
    sa.Column('pickup_delay_minutes', sa.FLOAT(), nullable=True),
    sa.Column('hour_of_day', sa.INTEGER(), nullable=True),
    sa.Column('prediction', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.drop_index(op.f('ix_agent_logs_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_delivery_cases_id'), table_name='delivery_cases')
    op.drop_table('delivery_cases')
    # ### end Alembic commands ###
